#!/bin/sh
set -eu

has_package() {
    pacman -Qq "$1" >/dev/null 2>&1
}

enable_display_manager() {
    package=$1
    service=$2
    if has_package "$package"; then
        mkdir -p /etc/systemd/system
        ln -sf "/usr/lib/systemd/system/$service" /etc/systemd/system/display-manager.service
        exit 0
    fi
}

enable_display_manager plasma-login-manager plasmalogin.service
enable_display_manager sddm sddm.service
enable_display_manager gdm gdm.service
enable_display_manager cosmic-greeter cosmic-greeter.service
enable_display_manager ddm ddm.service
enable_display_manager lxdm lxdm.service
enable_display_manager lightdm lightdm.service

if has_package ly; then
    rm -f /etc/systemd/system/display-manager.service
    mkdir -p /etc/systemd/system/multi-user.target.wants
    ln -sf /usr/lib/systemd/system/ly@.service \
        /etc/systemd/system/multi-user.target.wants/ly@tty2.service
fi
