# SPDX-License-Identifier: CC0-1.0
---
dontChroot: false
timeout: 420
packagechooser_desktop:
  "":
    command: '/etc/calamares/scripts/configure-selected-desktop none "${USER}" "${gs[autoLoginUser]}"'
    timeout: 420
  "*":
    command: '/etc/calamares/scripts/configure-selected-desktop "${gs[packagechooser_desktop]}" "${USER}" "${gs[autoLoginUser]}"'
    timeout: 420
