# SPDX-License-Identifier: CC0-1.0
---
dontChroot: false
timeout: 420
autoLoginUser:
  "*":
    command: '-/etc/calamares/scripts/configure-display-manager --autologin-user "${gs[autoLoginUser]}"'
    timeout: 420
packagechooser_desktop:
  "":
    command: '-/etc/calamares/scripts/configure-selected-desktop none "${USER}"'
    timeout: 420
  "*":
    command: '-/etc/calamares/scripts/configure-selected-desktop "${gs[packagechooser_desktop]}" "${USER}"'
    timeout: 420
