# SPDX-License-Identifier: CC0-1.0
---
dontChroot: true
timeout: 300

packagechooser_repository:
  catos: "/usr/bin/true"
  cachyos: "/usr/bin/python3 /etc/calamares/scripts/cachyos-repository.py"
  "": "/usr/bin/false"
  "*": "/usr/bin/false"
